platform :ios, '11.0'
inhibit_all_warnings!

target 'Weather' do
  use_frameworks!
  
  pod 'HanekeSwift', :git => 'https://github.com/Haneke/HanekeSwift.git', :branch => 'master'	
  # Pods for Weather

  target 'WeatherTests' do
    inherit! :search_paths
  end

  target 'WeatherUITests' do
#    inherit! :search_paths
  end

end
