// 
//  WeatherInterfaces.swift
//  Weather
//
//  Created by Canh Tran Wizeline on 6/11/20.
//  Copyright © 2020 CanhTran. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

// Dependency
protocol WeatherDependencyInterface {
    func makeWeatherView() -> ViewInterface
}

// Router
protocol WeatherRouterInterface: NavigationRouterInterface {
}

// ViewController
protocol WeatherViewInterface: ViewInterface {
    func reloadData()
    func setLoadingVisible(_ visible: Bool)
}

// Presenter
protocol WeatherPresenterInterface: PresenterInterface {
    func numberOfForecast() -> Int
    func dataAtIndex(index: Int) -> Forecast?
    func refreshListData()
    func fetchWeatherData(keyword: String)
}

// Interactor
protocol WeatherInteractorInterface {
    func cleanUp()
    func fetchWeatherData(isCached: Bool, completion: @escaping (Result<[Forecast], NetworkError>) -> Void)
}
