// 
//  WeatherInterfaces.swift
//  Weather
//
//  Created by Canh Tran Wizeline on 6/11/20.
//  Copyright © 2020 CanhTran. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

// Dependency
protocol WeatherDependencyInterface {
    func makeWeatherView() -> ViewInterface
}

// Router
protocol WeatherRouterInterface: NavigationRouterInterface {
}

// ViewController
protocol WeatherViewInterface: ViewInterface {
}

// Presenter
protocol WeatherPresenterInterface: PresenterInterface {
}

// Interactor
protocol WeatherInteractorInterface {
}
