// 
//  WeatherViewController.swift
//  Weather
//
//  Created by Canh Tran Wizeline on 6/11/20.
//  Copyright © 2020 CanhTran. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class WeatherViewController: BaseViewController {
    // MARK: - Public Properties

    var presenter: WeatherPresenterInterface!

    // MARK: - LifeCycle

    override func viewDidLoad() {
        super.viewDidLoad()
        setupView()
        presenter.viewDidLoad()
    }

    // MARK: - Setup

    private func setupView() {
    }
}

// MARK: - WeatherViewInterface

extension WeatherViewController: WeatherViewInterface {
}
