// 
//  WeatherRouter.swift
//  Weather
//
//  Created by Canh Tran Wizeline on 6/11/20.
//  Copyright © 2020 CanhTran. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class WeatherRouter: NavigationRouter {
}

// MARK: - WeatherRouterInterface

extension WeatherRouter: WeatherRouterInterface {
}
