// 
//  WeatherPresenter.swift
//  Weather
//
//  Created by Canh Tran Wizeline on 6/11/20.
//  Copyright © 2020 CanhTran. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class WeatherPresenter {
    // MARK: - Private Properties

    private unowned let view: WeatherViewInterface
    private let interactor: WeatherInteractorInterface
    private let router: WeatherRouterInterface

    // MARK: - LifeCycle

    init(view: WeatherViewInterface,
         interactor: WeatherInteractorInterface,
         router: WeatherRouterInterface) {
        self.view = view
        self.interactor = interactor
        self.router = router
    }

    func viewDidLoad() {
    }
}

// MARK: - WeatherPresenterInterface

extension WeatherPresenter: WeatherPresenterInterface {
}
