// 
//  WeatherDependency.swift
//  Weather
//
//  Created by Canh Tran Wizeline on 6/11/20.
//  Copyright © 2020 CanhTran. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class WeatherDependency: WeatherDependencyInterface {
    // MARK: - Module Setup

    func makeWeatherView() -> ViewInterface {
        let view = WeatherViewController()

        let interactor = WeatherInteractor()
        let navigationController = UINavigationController()
        let router = WeatherRouter(rootController: navigationController)
        router.setRootView(view, animated: false)

        let presenter = WeatherPresenter(view: view, interactor: interactor, router: router)
        view.presenter = presenter

        return router.toController()
    }
}
