// 
//  WeatherPresenter.swift
//  Weather
//
//  Created by Canh Tran Wizeline on 6/11/20.
//  Copyright © 2020 CanhTran. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class WeatherPresenter {
    // MARK: - Private Properties

    private unowned let view: WeatherViewInterface
    private let interactor: WeatherInteractorInterface
    private let router: WeatherRouterInterface
    
    private var forecastList = [Forecast]() {
        didSet {
            view.reloadData()
        }
    }
    
    private var isLoading = false {
        didSet {
            view.setLoadingVisible(isLoading)
        }
    }

    // MARK: - LifeCycle

    init(view: WeatherViewInterface,
         interactor: WeatherInteractorInterface,
         router: WeatherRouterInterface) {
        self.view = view
        self.interactor = interactor
        self.router = router
    }

    func viewDidLoad() {
        if !AppUserDefault.kLastKeyword.isEmpty {
            fetchWeatherData(keyword: AppUserDefault.kLastKeyword)
        }
    }
}

// MARK: - WeatherPresenterInterface

extension WeatherPresenter: WeatherPresenterInterface {
    func numberOfForecast() -> Int {
        return forecastList.count
    }
    
    func dataAtIndex(index: Int) -> Forecast? {
        return forecastList[safe: index]
    }
    
    func refreshListData() {
        // TODO:
    }
    
    func fetchWeatherData(keyword: String) {
        interactor.fetchWeatherData(isCached: false) { [weak self] (result) in
            guard let self = self else { return }
            switch result {
            case .success(let forecasts):
                self.forecastList = forecasts
            case .failure(let error):
                self.router.showAlert(title: "Error", message: error.localizedDescription)
            }
        }
    }
    
}
