// ___FILEHEADER___
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

// Dependency
protocol ___VARIABLE_moduleName___DependencyInterface {
    func make___VARIABLE_moduleName___View() -> ViewInterface
}

// Router
protocol ___VARIABLE_moduleName___RouterInterface: NavigationRouterInterface {
}

// ViewController
protocol ___VARIABLE_moduleName___ViewInterface: ViewInterface {
}

// Presenter
protocol ___VARIABLE_moduleName___PresenterInterface: PresenterInterface {
}

// Interactor
protocol ___VARIABLE_moduleName___InteractorInterface {
}
