// ___FILEHEADER___
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class ___VARIABLE_moduleName___Interactor {
    // MARK: - Private Properties
    private let networkClient: NetworkRequestable

    // MARK: - LifeCycle

    init(networkClient: NetworkRequestable = NetworkClient()) {
        self.networkClient = networkClient
    }
}

// MARK: - ___VARIABLE_moduleName___InteractorInterface

extension ___VARIABLE_moduleName___Interactor: ___VARIABLE_moduleName___InteractorInterface {
}
