// ___FILEHEADER___
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class ___VARIABLE_moduleName___Router: ViewRouter {
}

// MARK: - ___VARIABLE_moduleName___RouterInterface

extension ___VARIABLE_moduleName___Router: ___VARIABLE_moduleName___RouterInterface {
}
